### ISSUE TITLE
Windows 7x64 cannot use spawn() to non exe files. 

### ISSUE THREAD

**Issue by kthakore** [mcwhittemore/node-hooks#23]
I comment here:
https://github.com/mcwhittemore/node-hooks/issues/14

In pre-commit and post-commit hook files you are using spawn to to call ./bin/hooks.

./bin/hooks is a .cmd file. In windows due to:

https://github.com/joyent/node/issues/2318

spawn doesn't handle .bat or .cmd files so you will have to use:

`require('child_process').spawn('cmd', ['/s', '/c', '"./bin/hooks.cmd"'], { 
  windowsVerbatimArguments: true
});`

**Comment by mcwhittemore** [comment]
Sorry, this project has been discontinued.
